project:
  type: website
  output-dir: docs

website:
  title: "Andrej Zaslove"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - publications.qmd
      - shiny_apps.qmd

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true



